// 前台文案初始值（Saleor「模型」中的 Storefront — * 页面），由 setup.mjs 在页面不存在时创建。
// 页面已存在时不会覆盖，之后在后台「内容 → 模型」中修改即可；中文、日文在后台「翻译」中修改。
//
// 与内容页（配送信息、退换政策等）一致：英文为主语言，ZH_HANS / JA 为翻译。
// {freeShippingThreshold}、{returnsWindowDays}、{amount}、{label} 是前台替换的占位符，翻译中也要保留。
// 免运费门槛由前台从后台「配送方式」中免运费规则的最低订单金额实时读取，不在模型中设置。

// 字段名对应 schema.json 中 contentAttributes 的 name
export const MODELS = [
  {
    slug: 'storefront-policy',
    title: 'Storefront Policies',
    modelType: 'storefront-policies',
    // 免运费门槛不在这里设置（前台从配送方式读取）
    attributes: {
      'Returns window days': 14,
    },
  },
  {
    slug: 'storefront-chrome',
    title: 'Storefront Chrome',
    modelType: 'storefront-chrome',
    attributes: {
      'Announcement message': 'Free shipping on orders over {freeShippingThreshold}',
      'Announcement dismissible': true,
      'Nav all products label': 'All',
      'Nav view all label': 'View all {label}',
    },
    translations: {
      ZH_HANS: {
        'Announcement message': '订单满 {freeShippingThreshold} 免运费',
        'Nav all products label': '全部',
        'Nav view all label': '查看全部{label}',
      },
      JA: {
        'Announcement message': '{freeShippingThreshold}以上のご注文で送料無料',
        'Nav all products label': 'すべて',
        'Nav view all label': '{label}をすべて見る',
      },
    },
  },
  {
    slug: 'storefront-products',
    title: 'Storefront Products',
    modelType: 'storefront-products',
    attributes: {
      'Listing title': 'All Products',
      'Listing description': 'Denim and essentials, made to be worn for years.',
    },
    translations: {
      ZH_HANS: { 'Listing title': '全部商品', 'Listing description': '牛仔与日常单品，经得起岁月的穿着。' },
      JA: { 'Listing title': 'すべての商品', 'Listing description': '長く着られるデニムとベーシックアイテム。' },
    },
  },
  {
    slug: 'storefront-homepage',
    title: 'Storefront Homepage',
    modelType: 'storefront-homepage',
    // 首页大图沿用旧首页（页面 home-hero）的图片，见 setup.mjs
    heroImageFromPage: 'home-hero',
    attributes: {
      'Hero eyebrow': 'PINSO Denim',
      'Hero heading': 'Poetry Woven in Fabric',
      'Hero subheading': 'From fabric to silhouette, every piece is a commitment to quality and timeless style.',
      'Hero CTA label': 'Explore the Collection',
      'Featured heading': 'Featured Pieces',
      'Featured collection': { collection: 'featured' },
      'Featured limit': 8,
      'Categories heading': 'Shop by Category',
      'Categories eyebrow': 'Find your style',
      'Brand story heading': 'Our Story',
      'Brand story paragraph 1': 'We believe clothing is not merely a covering but an extension of personal style and inner character.',
      'Brand story paragraph 2': 'From the choice of fabric to the final stitch, every PINSO piece is made to be worn, washed and loved for years.',
      'Values heading': 'Our Promise',
      'Values columns desktop': '3',
      'Values column 1 title': 'Curated Fabrics',
      'Values column 1 text': 'Premium natural fibers sourced globally for touch and durability.',
      'Values column 2 title': 'Artisan Craft',
      'Values column 2 text': 'Every piece passes through artisan hands, attentive to every detail.',
      'Values column 3 title': 'Easy Returns',
      'Values column 3 text': 'Unworn items with original tags can be returned within {returnsWindowDays} days.',
      'Editorial heading': 'Timeless Style',
      'Editorial paragraph 1': 'We do not chase trends — we create classics that endure, season after season.',
      'Editorial image position': 'right',
      'Editorial CTA label': 'Shop All',
      'Photo credits': '[]',
    },
    translations: {
      ZH_HANS: {
        'Hero eyebrow': 'PINSO 品帅牛仔',
        'Hero heading': '以织物书写的诗意',
        'Hero subheading': '从面料到廓形，每一件单品都是对品质与永恒风格的承诺。',
        'Hero CTA label': '探索系列',
        'Featured heading': '精选单品',
        'Categories heading': '品类导览',
        'Categories eyebrow': '找到属于你的风格',
        'Brand story heading': '品牌故事',
        'Brand story paragraph 1': '我们相信，衣服不只是遮蔽身体，更是个人风格与内在气质的延伸。',
        'Brand story paragraph 2': '从选料到最后一道缝线，每一件 PINSO 都为经年穿着、反复洗涤、长久珍爱而做。',
        'Values heading': '品牌承诺',
        'Values column 1 title': '甄选面料',
        'Values column 1 text': '全球甄选优质天然纤维，兼顾触感与耐穿。',
        'Values column 2 title': '匠人手作',
        'Values column 2 text': '每一件单品经匠人之手，注重每个细节。',
        'Values column 3 title': '无忧退换',
        'Values column 3 text': '吊牌完好、未穿着的商品，签收后 {returnsWindowDays} 天内可退换。',
        'Editorial heading': '永恒风格',
        'Editorial paragraph 1': '不追逐潮流，只创造经得起时间考验的经典。',
        'Editorial CTA label': '浏览全部商品',
      },
      JA: {
        'Hero eyebrow': 'PINSO Denim',
        'Hero heading': '織物が紡ぐ詩',
        'Hero subheading': '素材からシルエットまで、すべてのアイテムに品質と時代を超えるスタイルへのこだわりを。',
        'Hero CTA label': 'コレクションを見る',
        'Featured heading': 'おすすめアイテム',
        'Categories heading': 'カテゴリーから選ぶ',
        'Categories eyebrow': 'あなたのスタイルを見つける',
        'Brand story heading': 'ブランドストーリー',
        'Brand story paragraph 1': '服は身体を覆うだけのものではなく、その人のスタイルと内面の延長だと私たちは考えます。',
        'Brand story paragraph 2': '素材選びから最後のひと針まで、PINSO のアイテムは長く着て、洗って、愛されるために作られています。',
        'Values heading': 'ブランドの約束',
        'Values column 1 title': '厳選素材',
        'Values column 1 text': '世界中から厳選した上質な天然繊維で、肌ざわりと耐久性を両立。',
        'Values column 2 title': '職人技',
        'Values column 2 text': 'すべてのアイテムは職人の手を経て、細部までこだわります。',
        'Values column 3 title': 'かんたん返品',
        'Values column 3 text': 'タグ付きの未着用品は、お届けから{returnsWindowDays}日以内に返品できます。',
        'Editorial heading': '時代を超えるスタイル',
        'Editorial paragraph 1': 'トレンドを追わず、季節を越えて着られるクラシックを。',
        'Editorial CTA label': 'すべての商品を見る',
      },
    },
  },
  {
    slug: 'storefront-cart',
    title: 'Storefront Cart',
    modelType: 'storefront-cart',
    attributes: {
      'Empty title': 'Your bag is empty',
      'Empty body': "Looks like you haven't added anything to your bag yet.",
      'Empty CTA label': 'Start Shopping',
      'Trust free shipping prefix': 'Free delivery over',
      'Trust returns label': '{returnsWindowDays}-day returns',
      'Drawer title': 'Your Bag',
      'Drawer add for free shipping': 'Add {amount} more for free shipping',
      'Drawer free shipping qualified': 'You qualify for free shipping!',
    },
    translations: {
      ZH_HANS: {
        'Empty title': '购物袋是空的',
        'Empty body': '你还没有把任何商品加入购物袋。',
        'Empty CTA label': '开始购物',
        'Trust free shipping prefix': '满额免运费',
        'Trust returns label': '{returnsWindowDays} 天退换',
        'Drawer title': '购物袋',
        'Drawer add for free shipping': '再买 {amount} 即可免运费',
        'Drawer free shipping qualified': '已享受免运费！',
      },
      JA: {
        'Empty title': 'カートは空です',
        'Empty body': 'まだ商品が追加されていません。',
        'Empty CTA label': 'ショッピングを始める',
        'Trust free shipping prefix': '送料無料',
        'Trust returns label': '{returnsWindowDays}日間返品可能',
        'Drawer title': 'カート',
        'Drawer add for free shipping': 'あと {amount} で送料無料',
        'Drawer free shipping qualified': '送料無料が適用されます！',
      },
    },
  },
  {
    slug: 'storefront-checkout',
    title: 'Storefront Checkout',
    modelType: 'storefront-checkout',
    attributes: {
      'Empty cart title': 'Your bag is empty',
      'Empty cart body': "Looks like you haven't added anything to your bag yet.",
      'Empty cart start label': 'Start Shopping',
      'Empty cart go back label': 'Go back',
      'Empty session title': 'Your bag is empty',
      'Empty session message': 'Add items from the store, then return here to complete your purchase.',
      'Marketing opt-in label': 'Email me with news and offers',
      'Trust secure checkout': 'Secure checkout',
      'Trust Stripe processor': 'Payments are processed securely',
    },
    translations: {
      ZH_HANS: {
        'Empty cart title': '购物袋是空的',
        'Empty cart body': '你还没有把任何商品加入购物袋。',
        'Empty cart start label': '开始购物',
        'Empty cart go back label': '返回',
        'Empty session title': '购物袋是空的',
        'Empty session message': '请先在商店中挑选商品，再回到这里完成购买。',
        'Marketing opt-in label': '通过邮件接收新品与优惠信息',
        'Trust secure checkout': '安全结算',
        'Trust Stripe processor': '付款经过安全加密处理',
      },
      JA: {
        'Empty cart title': 'カートは空です',
        'Empty cart body': 'まだ商品が追加されていません。',
        'Empty cart start label': 'ショッピングを始める',
        'Empty cart go back label': '戻る',
        'Empty session title': 'カートは空です',
        'Empty session message': 'ストアで商品を追加してから、ここに戻って購入を完了してください。',
        'Marketing opt-in label': '新着情報やお得な情報をメールで受け取る',
        'Trust secure checkout': '安全な決済',
        'Trust Stripe processor': 'お支払いは安全に処理されます',
      },
    },
  },
];
